### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by jane-pyc** [3dlg-hcvc/bioscan-clip#1]
I really like your article, and the code structure is also very clearly written. Thank you again for your work.

I have a question about the training part of `train_cl.py. `
I see that the code passes in `different ckpt models` for image, DNA, and text encoder, respectively. Is this the model you trained?

Could you please provide the training code or have the opportunity to publish it?

I look forward to your reply.

**Comment by atwang16** [comment]
Hi @jane-pyc , thank you for reaching out, and we are glad you are interested in our work!
The checkpoint models used in the training code are pretrained models from different sources. The BarcodeBERT model for encoding DNA can be downloaded per the README instructions, and the other two (for images and text) are base pretrained ViT and BERT models, respectively, which should be loaded directly in the code, without requiring extra libraries. With the BarcodeBERT model saved on your machine, you should be able to just use the `train_cl.py` script after that.

Once you are done training, it should produce a single checkpoint for all of the encoders which can be used in the inference and evaluation script, rather than having to maintain three separate checkpoints afterward.

**Comment by jane-pyc** [comment]
Thank you very much for your reply. The code you organized is very clear and the code structure is very elegant!

Thanks for your reply, my previous question has been completely clarified. I wish you a speedy recovery!
