### ISSUE TITLE
bioscan_data and insect_data

### ISSUE THREAD

**Issue by jane-pyc** [3dlg-hcvc/bioscan-clip#2]
I really like your article, and the code structure is also very clearly written. Thank you again for your work.
I have a question about the data sets `bioscan_data and insect_data`.

For bioscan_data, it is mentioned in the `global_config.yaml` file that the input data files include tsv and json documents. Regarding the hdf5 file, you have provided a download link. Do you have a download link for the other two files?

In addition, for insect_data, it is mentioned in the `global_config.yaml` file that the input data files include a series of mat, hdf5, csv, json files and images folders. Do you have a download link for these data?

I look forward to your reply.

**Comment by zmgong** [comment]
Hi @jane-pyc ,  thank you! 

For bioscan_data, I'll provide the link for downloading the TSV and images in the readme soon (I think you can also download them from bioscan-1m and bioscan-5m's repository. I'll put the link in the readme as well). I don't think the JSON file is actually necessary anymore; we will keep working on the code cleaning and refactoring soon and maybe just remove it.

For the INSECT dataset, It may take some time for me to clean the code for the relevant experiments. I'll try to get it done as soon as possible, but due to my personal health condition, I may need to have surgery soon... so this might be delayed.

**Comment by jane-pyc** [comment]
Thank you very much for your reply. I will carefully review the code you have just released.

I wish you a speedy recovery!
